### ISSUE TITLE
[SYMFONY 7] - Error when trying to create controller

### ISSUE THREAD

**Issue by thedevopser** [thewalkingcoder/maker-bundle#4]
Hi,

There is an issue when we try to create a controller 

![Image](https://github.com/user-attachments/assets/195c23a9-f1e4-4520-a299-793e85de65c5)

Stack : 

- Symfony 7.2
- Php 8.3
- Bundle version : 7.0.2

```yaml
//twc_maker.yaml

twc_maker:
  entity:
    - { context: 'parameters', target_entity: 'App\Parameters\Domain\Entity', target_repository: 'App\Parameters\Infrastructure\Doctrine' }
    - { context: 'user', target_entity: 'App\User\Domain\Entity', target_repository: 'App\User\Infrastructure\Doctrine' }
    - { context: 'api', target_entity: 'App\Api\Domain\Entity', target_repository: 'App\Api\Infrastructure\Doctrine' }
  
  controller:
    - { context: 'parameters', target: 'App\Parameters\Presenter\Controller' }
    - { context: 'user', target: 'App\User\Presenter\Controller' }
    - { context: 'api', target: 'App\Api\Presenter\Controller' }
    - { context: 'home', target: 'App\Home\Presenter\Controller' }
  
  message:
    - { context: 'parameters.command', target: 'App\Parameters\Application\Command' }
    - { context: 'parameters.query', target: 'App\Parameters\Application\Query' }
    - { context: 'parameters.event', target: 'App\Parameters\Application\Event' }
    - { context: 'user.command', target: 'App\User\Application\Command' }
    - { context: 'user.query', target: 'App\User\Application\Query' }
    - { context: 'user.event', target: 'App\User\Application\Event' }
    - { context: 'api.command', target: 'App\Api\Application\Command' }
    - { context: 'api.query', target: 'App\Api\Application\Query' }
    - { context: 'api.event', target: 'App\Api\Application\Event' }
  
  form:
    - { context: 'parameters', target: 'App\Parameters\Presenter\Form' }
    - { context: 'user', target: 'App\User\Presenter\Form' }
    - { context: 'api', target: 'App\Api\Presenter\Form' }
  
  command:
    - { context: 'parameters', target: 'App\Parameters\Presenter\Console' }
    - { context: 'user', target: 'App\User\Presenter\Console' }
    - { context: 'api', target: 'App\Api\Presenter\Console' }
  
  voter:
    - { context: 'parameters', target: 'App\Parameters\Presenter\Voter' }
    - { context: 'user', target: 'App\User\Presenter\Voter' }
    - { context: 'api', target: 'App\Api\Presenter\Voter' }
 ```

Thanks for your help.

Regards
